### ISSUE TITLE
Stopwatch vs StopWatch

### ISSUE THREAD

**Issue by Avec112** [oswaldobapvicjr/performetrics#55]
First I will say great work you have done with Performetrics.

I noticed you have named the class `Stopwatch` and not `StopWatch`. Apache Commons Lang, Spring Framework, Guava and probably more all call it `StopWatch`. I do not know why all others have used a uppercase W since the word stopwatch is correct over "stop watch" and I will assume its how it started with the first one back in the days (Spring 2002 or something). 

I already had `StopWatch` in my code and after added Performetrics as dependency and removed the import statement I expected `Performetrics StopWatch` to be found in the path but I did not. 

Not a big deal but I thought you maybe would consider changing it. It might even result it more use if the dependency is already in the developers path.You could maybe make `Stopwatch extend StopWatch` and also deprecating it. That way you do not break anything and later you could remove it and all is good. 

Anyways whatever you decide you have made a great tool.

A couple of other things I noticed right after I had written the above regarding `Stopwatch`.
* `elapsedTime(..)` requires argument `Type` even when I initiated `Stopwatch` with `Type`. Here `elapsedTime()` could honor what was defined at initialization time. 
* `toString()` is not implemented but should probably return a default summary, details or something.

**Comment by oswaldobapvicjr** [comment]
Hey @Avec112, thanks for the feedback!
Happy to know that you like the tool.
I really enjoyed your hints and I'll surely implement them in the next release of Performetrics, which I am planning to have very soon (probably still this month).

**Comment by oswaldobapvicjr** [comment]
### Technical analysis/report
After a closer look at the suggestion of making `Stopwatch` extend `StopWatch` and also deprecating it, I decided **not** to go in this direction *(for now)*, due to the following reasons:
- A public `StopWatch` class, should be defined in its own file, so it must be placed on a different folder/package. So, to maintain compatibility, it should be in the opposite direction: having the new `StopWatch` extending `Stopwatch`, with the new class in a different package;
- While **Apache Commons** and **Spring** name their objects as `StopWatch`, **Google Guava** uses `Stopwatch`

The other suggestions provided are **approved** and will be implemented soon.

### Task list
- [x] `toString()` implementation
- [x] zero-argument `elapsedTime()` implementation for Stopwatch with a single counter type

**Comment by oswaldobapvicjr** [comment]
Enhancement implemented at `master`. Will be available on the next release of Performetrics  (v2.2.4)
